const assert=require('node:assert/strict');
const B=require('./builder-model');
const stock=B.ticker;
const condition={incantation_type:'IfElse',condition:{condition_type:'SingleCondition',type:'BothIndicators',lh_ticker_symbol:'SPY',lh_indicator:{type:'CurrentPrice',window:0},rh_ticker_symbol:'SPY',rh_indicator:{type:'MovingAverage',window:200},greater_than:false,for_days:1},then_incantation:stock('QQQ'),else_incantation:stock('BIL')};
let original=B.group([stock('SPY')]);
let added=B.change(original,'0','add',condition);
assert.equal(original.incantations.length,1);
assert.equal(added.incantations[1].condition.rh_indicator.window,200);
let nested=B.change(added,'0-1','add',stock('GLD'),'else');
assert.equal(nested.incantations[1].then_incantation.symbol,'QQQ');
assert.deepEqual(nested.incantations[1].else_incantation.incantations.map(n=>n.symbol),['BIL','GLD']);
let custom={incantation_type:'Weighted',type:'Custom',weights:[.7,.3],incantations:[stock('SPY'),stock('QQQ')]};
let more=B.change(custom,'0','add',stock('GLD'));
assert.ok(Math.abs(more.weights.reduce((a,b)=>a+b,0)-1)<1e-12);
assert.ok(Math.abs(more.weights[0]/more.weights[1]-7/3)<1e-12);
let dup=B.change(custom,'0-0','duplicate');assert.deepEqual(dup.weights,[.35,.35,.3]);
assert.deepEqual(B.change(dup,'0-1','delete').weights,[.35,.3]);
assert.throws(()=>B.change(added,'0-1-0','delete'),/分支/);
assert.throws(()=>stock('<script>'));
let wrapped=B.change({name:'outer',incantation:original},'0-0','edit',stock('AAPL'));
assert.equal(wrapped.name,'outer');assert.equal(wrapped.incantation.incantations[0].symbol,'AAPL');
assert.deepEqual(JSON.parse(JSON.stringify(nested)),nested);
if(process.argv.includes('--fixture'))process.stdout.write(JSON.stringify(added));
else console.log('PASS: native add, nested ELSE, SMA200, custom weights, duplicate/delete guards, wrapper preservation, JSON round-trip');
