// Isolated browser context: never touches the user's open tab or saved strategies.
const {chromium}=require('playwright');
const assert=require('node:assert/strict');
(async()=>{
 const browser=await chromium.launch({channel:'msedge',headless:true});
 const context=await browser.newContext();const page=await context.newPage();const errors=[];
 page.on('pageerror',error=>errors.push(error.message));
 page.on('dialog',dialog=>dialog.accept());
 await page.goto('http://127.0.0.1:8766/?v=20260903-22');
 await page.locator('#newBtn').click();
 await page.locator('#addRoot').click();
 await page.locator('#nodeSymbol').fill('SPY');
 await page.locator('#nodeBuilderForm button[type=submit]').click();
 assert.match(await page.locator('#tree').innerText(),/SPY/);
 await page.locator('#addRoot').click();
 await page.locator('#nodeKind').selectOption('condition');
 await page.locator('#nodeBuilderForm button[type=submit]').click();
 assert.match(await page.locator('#tree').innerText(),/200日均线/);
 assert.equal(await page.locator('.node[data-path="0-0"] > .node-row .node-allocation').textContent(),'50%');
 assert.equal(await page.locator('.node[data-path="0-1-0"] > .node-row .node-allocation').textContent(),'选中时 100%');
 await page.locator('.node[data-path="0-0"] > .node-row .node-allocation').click();
 await page.locator('#groupType').selectOption('Custom');
 await page.locator('#groupWeights').fill('15,85');
 await page.locator('#nodeBuilderForm button[type=submit]').click();
 assert.equal(await page.locator('.node[data-path="0-0"] > .node-row .node-allocation').textContent(),'15%');
 assert.equal(await page.locator('.node[data-path="0-1"] > .node-row .node-allocation').textContent(),'85%');
 const inline=page.locator('.inline-condition');
 assert.equal(await inline.isVisible(),false,'Parameters are collapsed by default');
 await page.getByRole('button',{name:'展开参数',exact:true}).click();
 assert.equal(await inline.isVisible(),true);
 await inline.locator('select[aria-label="右侧指标"]').selectOption('ExponentialMovingAverage');
 await page.getByRole('button',{name:'收起参数',exact:true}).click();
 assert.equal(await inline.isVisible(),false);
 await page.getByRole('button',{name:'展开参数',exact:true}).click();
 assert.equal(await inline.locator('select[aria-label="右侧指标"]').inputValue(),'ExponentialMovingAverage','Collapsing preserves unapplied input');
 await inline.getByRole('button',{name:'应用',exact:true}).click();
 assert.equal(await inline.isVisible(),false,'Applied parameters return to compact view');
 assert.match(await page.locator('#tree').innerText(),/指数均线/);
 await page.locator('#undoBtn').click();assert.match(await page.locator('#tree').innerText(),/200日均线/);
 await page.locator('#redoBtn').click();assert.match(await page.locator('#tree').innerText(),/指数均线/);
 await page.locator('.node[data-path="0-1"] > .node-row button[title="在此模块添加股票或指标分支"]').click();
 await page.locator('#nodeLeg').selectOption('else');await page.locator('#nodeSymbol').fill('GLD');
 await page.locator('#nodeBuilderForm button[type=submit]').click();
 assert.match(await page.locator('.node[data-path="0-1-1"]').innerText(),/GLD/);
 await page.getByRole('button',{name:'代码编辑器',exact:true}).click();
 const definition=JSON.parse(await page.locator('#strategyCode').inputValue());
 assert.equal(definition.incantations[1].condition.rh_indicator.type,'ExponentialMovingAverage');
 assert.deepEqual(definition.incantations[1].else_incantation.incantations.map(n=>n.symbol),['BIL','GLD']);
 let saved;
 await page.route('**/api/strategies',async route=>{
   if(route.request().method()==='POST'){saved=route.request().postDataJSON();await route.fulfill({json:{id:'isolated-builder-test',name:saved.name}});}
   else await route.continue();
 });
 await page.locator('#saveBtn').click();
 await page.waitForFunction(()=>document.querySelector('#undoBtn').disabled);
 assert.deepEqual(saved.strategy.definition,definition);
 assert.deepEqual(errors,[]);
 console.log('PASS: browser stock/condition creation, inline indicator change, undo/redo, nested ELSE, executable JSON, save payload and undo baseline; no page errors');
 await browser.close();
})().catch(error=>{console.error(error);process.exit(1)});
